const copy = {
  en: {
    app: {
      utilityPrimary: "Government of Karnataka Civic Issue Portal",
      utilitySecondary: "Bengaluru Urban Reporting Interface",
      languageLabel: "Language",
      themeLabel: "Theme",
      lightMode: "Light",
      darkMode: "Dark",
      home: "Home",
      reportIssue: "Report Issue",
      adminHub: "Admin Hub",
      login: "Login",
      switchAccount: "Switch Account",
      logout: "Logout",
      eyebrow: "City-wide civic issue visibility for Bengaluru",
      title: "Silicon Sentry",
      subtitle: "Where public issue reporting converges",
    },
    home: {
      eyebrow: "National portal inspired civic experience",
      title: "Report and monitor public issues across Bengaluru with clarity and structure.",
      description:
        "Silicon Sentry helps residents flag road, water, sanitation, safety, and infrastructure issues across the city while giving administrators a clearer operational view of where attention is needed.",
      primaryAction: "Submit an issue",
      secondaryAction: "Open admin hub",
      mapEyebrow: "Public service view",
      metrics: [
        {
          title: "Geo-tagged intake",
          body: "Attach coordinates to route Bengaluru field issues faster.",
        },
        {
          title: "Civic category routing",
          body: "Structure reports by roads, water, sanitation, safety, and more.",
        },
        {
          title: "Heat map oversight",
          body: "Spot concentrated issue zones across the city more quickly.",
        },
      ],
      chips: [
        "Roads",
        "Water Supply",
        "Sanitation",
        "Street Lights",
        "Public Safety",
        "Public Transport",
      ],
      problemEyebrow: "Problem statement",
      problemTitle: "Why this platform matters",
      problemBodyOne:
        "Governments receive large numbers of complaints related to roads, sanitation, utilities, transportation, and public services. Manual processing makes it difficult to categorize, prioritize, and resolve these issues efficiently.",
      problemBodyTwo:
        "Silicon Sentry addresses that gap by helping authorities respond faster, detect recurring patterns, and improve accountability in civic issue resolution.",
      challengeEyebrow: "Design challenge",
      challengeTitle: "AI-assisted grievance operations",
      challengeBody:
        "The platform is designed to analyze citizen complaints using natural language processing, surface hotspots and trends, and provide administrators with a dashboard to track resolution progress in one place.",
      howEyebrow: "How It Works",
      howTitle: "From complaint submission to resolution tracking",
      steps: [
        {
          title: "Citizen submits complaint",
          body: "Residents report civic issues with category, description, and optional location details.",
        },
        {
          title: "System categorizes and prioritizes",
          body: "Structured inputs and NLP logic identify issue type, urgency, and likely problem clusters.",
        },
        {
          title: "Dashboard reveals trends",
          body: "Authorities monitor category trends, department load, and city hotspots through charts and heat maps.",
        },
        {
          title: "Resolution is tracked",
          body: "Admins assign departments, update status, log notes, and maintain a visible resolution timeline.",
        },
      ],
      residentEyebrow: "For Bengaluru residents",
      residentTitle: "Fast, structured reporting",
      residentBody:
        "Submit civic issues with category selection, location context, and clear descriptions from mobile or desktop.",
      adminEyebrow: "For city administrators",
      adminTitle: "A clearer operations picture",
      adminBody:
        "Review issue trends, inspect city hotspots, and log response quality without jumping between tools.",
    },
    login: {
      eyebrow: "Secure access",
      title: "Sign in to Silicon Sentry",
      body:
        "Choose a role to enter the citizen complaint flow or the admin command center.",
      signupTitle: "Create your Silicon Sentry account",
      signupBody: "Sign up as a citizen user to report civic issues and track updates.",
      signIn: "Sign in",
      userRole: "User login",
      adminRole: "Admin login",
      signup: "Sign up",
      name: "Full name",
      email: "Email",
      password: "Password",
      signingIn: "Signing in...",
      signInAs: "Sign in as",
      createAccount: "Create account",
      forgotPassword: "Forgot your password?",
      forgotPasswordInfo: "Password reset is not configured yet. Contact the administrator.",
      backToSignIn: "Back to sign in",
      signupSuccess: "Account created successfully. You can now sign in.",
      signupFailed: "Signup failed.",
      loginFailed: "Login failed.",
    },
    submit: {
      eyebrow: "Bengaluru issue reporting",
      title: "Submit a civic issue with map details",
      reportsEyebrow: "My reports",
      reportsTitle: "Track your issues and add reviews",
      reportsBody:
        "Once a complaint is logged, you can leave a review here based on how the issue was handled.",
      loading: "Loading your issues...",
      empty: "You have not submitted any issues yet.",
      reporterLabel: "Submitted by",
      locationLabel: "Location",
      noLocation: "No location attached",
      sentimentLabel: "Sentiment",
      assignedLabel: "Assigned",
      resolutionTitle: "Resolution update",
      timelineTitle: "Progress timeline",
      noReviews: "No reviews added yet.",
      attachmentsTitle: "Attached photos",
    },
    userDashboard: {
      eyebrow: "Citizen workspace",
      titleSuffix: "'s dashboard",
      body: "Review your reported issues, see current status, and move quickly to file a new complaint.",
      newIssue: "File new complaint",
      myReports: "Jump to reports",
      totalReports: "My complaints",
      openReports: "Open",
      resolvedReports: "Resolved",
      totalSupports: "Support votes",
      recentTitle: "Recent complaints",
      recentBody: "Your latest reported issues appear here for quick follow-up.",
      empty: "You have not submitted any complaints yet.",
      location: "Location",
      assigned: "Assigned",
      supports: "Supports",
    },
    form: {
      name: "Full name",
      email: "Email",
      department: "Civic department or ward",
      departmentPlaceholder: "BBMP ward, BWSSB, traffic police, BESCOM...",
      category: "Category",
      subject: "Subject",
      description: "Description",
      photos: "Issue photos",
      photoHelp: "Add up to 3 photos to document the issue.",
      removePhoto: "Remove",
      mapEyebrow: "Map integration",
      mapTitle: "Attach issue location",
      useMyLocation: "Use my location",
      locating: "Locating...",
      locationLabel: "Location label",
      locationPlaceholder: "MG Road signal, Indiranagar 100 Ft Road, Ward office...",
      latitude: "Latitude",
      longitude: "Longitude",
      submit: "Submit issue",
      submitting: "Submitting...",
      success: "Complaint submitted successfully.",
      geolocationUnsupported: "Geolocation is not supported in this browser.",
      geolocationFailed: "Unable to fetch your location. You can still enter it manually.",
      photoTypeError: "Please upload image files only.",
      photoLimitError: "You can upload up to 3 photos per issue.",
    },
    review: {
      reviewerName: "Reviewer name",
      stars: "stars",
      comment: "Review comment",
      saving: "Saving...",
      add: "Add review",
      success: "Review recorded.",
      failed: "Unable to add review.",
    },
    admin: {
      eyebrow: "Operations center",
      titleSuffix: "'s command center",
      body:
        "Monitor Bengaluru complaint volume, detect trends, assign departments, and track resolution progress from a single admin workspace.",
      totalIssues: "Total issues",
      openCases: "Open cases",
      resolved: "Resolved",
      resolutionRate: "Resolution rate",
      departmentEyebrow: "Department performance",
      departmentTitle: "Assignment distribution",
      departmentName: "Department",
      assignedCount: "Assigned",
      resolvedCount: "Resolved",
      slaCompliance: "SLA compliance",
      noAssignments: "No department assignments yet.",
      heatEyebrow: "Spatial intelligence",
      heatTitle: "Issue heat map",
      heatBody: "Explore complaint hotspots directly on the map of Bengaluru.",
      filtersEyebrow: "Filters and search",
      filtersTitle: "Trend analysis controls",
      searchPlaceholder: "Search subject, location, or reporter",
      allStatuses: "All statuses",
      allCategories: "All categories",
      allAssignments: "All assignments",
      workflowEyebrow: "Resolution workflow",
      workflowTitle: "Issue management list",
      loading: "Loading issues...",
      noMatches: "No issues match the selected filters.",
      reporter: "Reporter",
      sentiment: "Sentiment",
      assigned: "Assigned",
      location: "Location",
      noLocation: "No location attached",
      status: "Status",
      assignedDepartment: "Assigned department",
      resolutionNotes: "Resolution notes",
      resolutionPlaceholder: "Add action taken, next steps, or closure notes",
      timelineTitle: "Progress timeline",
      attachmentsTitle: "Attached photos",
    },
    charts: {
      distributionEyebrow: "Distribution",
      byCategory: "Category distribution",
      priorityEyebrow: "Trend monitor",
      byPriority: "Filed vs resolved (6 Mo)",
    },
    heatmap: {
      title: "Bengaluru issue heat map",
      legendTitle: "Heat map legend",
      legendBody: "Markers summarize mapped complaints by priority across Bengaluru.",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    shared: {
      roads: "Roads",
      waterSupply: "Water Supply",
      sanitation: "Sanitation",
      streetLights: "Street Lights",
      publicSafety: "Public Safety",
      parks: "Parks and Public Spaces",
      publicTransport: "Public Transport",
      otherIssue: "Other Civic Issue",
      open: "Open",
      inProgress: "In Progress",
      resolved: "Resolved",
    },
  },
  kn: {
    app: {
      utilityPrimary: "ಕರ್ನಾಟಕ ಸರ್ಕಾರ ನಾಗರಿಕ ಸಮಸ್ಯೆ ಪೋರ್ಟಲ್",
      utilitySecondary: "ಬೆಂಗಳೂರು ನಗರ ವರದಿ ವೇದಿಕೆ",
      languageLabel: "ಭಾಷೆ",
      themeLabel: "ಥೀಮ್",
      lightMode: "ಬೆಳಕು",
      darkMode: "ಗಾಢ",
      home: "ಮುಖಪುಟ",
      reportIssue: "ಸಮಸ್ಯೆ ವರದಿ",
      adminHub: "ನಿರ್ವಹಣಾ ಕೇಂದ್ರ",
      login: "ಲಾಗಿನ್",
      switchAccount: "ಖಾತೆ ಬದಲಿಸಿ",
      logout: "ಲಾಗ್ ಔಟ್",
      eyebrow: "ಬೆಂಗಳೂರು ನಗರಮಟ್ಟದ ನಾಗರಿಕ ಸಮಸ್ಯೆ ದೃಶ್ಯತೆ",
      title: "Silicon Sentry",
      subtitle: "ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆ ವರದಿ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ",
    },
    home: {
      eyebrow: "ರಾಷ್ಟ್ರೀಯ ಪೋರ್ಟಲ್ ಶೈಲಿಯ ನಾಗರಿಕ ಅನುಭವ",
      title: "ಬೆಂಗಳೂರು ನಗರದ ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ಮತ್ತು ವ್ಯವಸ್ಥಿತವಾಗಿ ವರದಿ ಮಾಡಿ ಮತ್ತು ಗಮನಿಸಿ.",
      description:
        "Silicon Sentry ನಿವಾಸಿಗಳಿಗೆ ರಸ್ತೆ, ನೀರು, ಸ್ವಚ್ಛತೆ, ಭದ್ರತೆ ಮತ್ತು ಮೂಲಸೌಕರ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ನಗರಮಟ್ಟದಲ್ಲಿ ವರದಿ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಆಡಳಿತಕ್ಕೆ ಗಮನ ನೀಡಬೇಕಾದ ಪ್ರದೇಶಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ನೋಡಲು ಸಹ ಸಾಧ್ಯವಾಗುತ್ತದೆ.",
      primaryAction: "ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿ",
      secondaryAction: "ನಿರ್ವಹಣಾ ಕೇಂದ್ರ ತೆರೆಯಿರಿ",
      mapEyebrow: "ಸಾರ್ವಜನಿಕ ಸೇವಾ ನೋಟ",
      metrics: [
        {
          title: "ಜಿಯೋ-ಟ್ಯಾಗ್ ಮಾಡಿದ ದಾಖಲಾತಿ",
          body: "ಬೆಂಗಳೂರು ಕ್ಷೇತ್ರದ ಸಮಸ್ಯೆಗಳನ್ನು ವೇಗವಾಗಿ ತಲುಪಿಸಲು ಸ್ಥಳಾಂಶವನ್ನು ಸೇರಿಸಿ.",
        },
        {
          title: "ವಿಭಾಗವಾರು ವರ್ಗೀಕರಣ",
          body: "ರಸ್ತೆ, ನೀರು, ಸ್ವಚ್ಛತೆ, ಭದ್ರತೆ ಮತ್ತು ಇತರೆ ವಿಭಾಗಗಳಂತೆ ವರದಿಗಳನ್ನು ರಚಿಸಿ.",
        },
        {
          title: "ಹೀಟ್ ಮ್ಯಾಪ್ ಮೇಲ್ವಿಚಾರಣೆ",
          body: "ನಗರದ ಸಮಸ್ಯೆಗಳ ಕೇಂದ್ರೀಕೃತ ಪ್ರದೇಶಗಳನ್ನು ವೇಗವಾಗಿ ಗುರುತಿಸಿ.",
        },
      ],
      chips: [
        "ರಸ್ತೆಗಳು",
        "ನೀರಿನ ಸರಬರಾಜು",
        "ಸ್ವಚ್ಛತೆ",
        "ರಸ್ತೆ ದೀಪಗಳು",
        "ಸಾರ್ವಜನಿಕ ಭದ್ರತೆ",
        "ಸಾರ್ವಜನಿಕ ಸಾರಿಗೆ",
      ],
      problemEyebrow: "ಸಮಸ್ಯೆಯ ಹಿನ್ನೆಲೆ",
      problemTitle: "ಈ ವೇದಿಕೆ ಯಾಕೆ ಅಗತ್ಯ",
      problemBodyOne:
        "ಸರ್ಕಾರಗಳಿಗೆ ರಸ್ತೆ, ಸ್ವಚ್ಛತೆ, ಸಾರ್ವಜನಿಕ ಸೇವೆಗಳು, ವಿದ್ಯುತ್, ನೀರು ಮತ್ತು ಸಾರಿಗೆ ಕುರಿತ ಅನೇಕ ದೂರುಗಳು ಬರುತ್ತವೆ. ಕೈಯಾರೆ ಅವನ್ನು ಸಂಸ್ಕರಿಸುವುದರಿಂದ ಅವುಗಳನ್ನು ವರ್ಗೀಕರಿಸಲು, ಆದ್ಯತೆ ನೀಡಲು ಮತ್ತು ತ್ವರಿತವಾಗಿ ಪರಿಹರಿಸಲು ಕಷ್ಟವಾಗುತ್ತದೆ.",
      problemBodyTwo:
        "Silicon Sentry ಅಧಿಕಾರಿಗಳಿಗೆ ಶೀಘ್ರ ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಲು, ಮರುಕಳಿಸುವ ಮಾದರಿಗಳನ್ನು ಗುರುತಿಸಲು ಮತ್ತು ನಾಗರಿಕ ಸಮಸ್ಯೆಗಳ ಪರಿಹಾರದಲ್ಲಿ ಹೊಣೆಗಾರಿಕೆಯನ್ನು ಹೆಚ್ಚಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
      challengeEyebrow: "ಡಿಸೈನ್ ಸವಾಲು",
      challengeTitle: "AI ನೆರವಿನ ದೂರು ನಿರ್ವಹಣೆ",
      challengeBody:
        "ಈ ವೇದಿಕೆ ನೈಸರ್ಗಿಕ ಭಾಷಾ ಸಂಸ್ಕರಣೆಯನ್ನು ಬಳಸಿ ನಾಗರಿಕ ದೂರುಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ, ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ಮತ್ತು ಧೋರಣಿಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ ಮತ್ತು ಆಡಳಿತಕ್ಕೆ ಪರಿಹಾರ ಪ್ರಗತಿಯನ್ನು ಒಂದು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ನೋಡುವ ಅವಕಾಶ ಒದಗಿಸುತ್ತದೆ.",
      howEyebrow: "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
      howTitle: "ದೂರು ಸಲ್ಲಿಕೆಯಿಂದ ಪರಿಹಾರ ಟ್ರ್ಯಾಕಿಂಗ್ ವರೆಗೆ",
      steps: [
        {
          title: "ನಾಗರಿಕರು ದೂರು ಸಲ್ಲಿಸುತ್ತಾರೆ",
          body: "ವರ್ಗ, ವಿವರಣೆ ಮತ್ತು ಅಗತ್ಯವಿದ್ದರೆ ಸ್ಥಳ ವಿವರಗಳೊಂದಿಗೆ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಬಹುದು.",
        },
        {
          title: "ವ್ಯವಸ್ಥೆ ವರ್ಗೀಕರಿಸಿ ಆದ್ಯತೆ ನೀಡುತ್ತದೆ",
          body: "ರಚನೆಯಾದ ಇನ್‌ಪುಟ್ ಮತ್ತು NLP ತರ್ಕವು ಸಮಸ್ಯೆಯ ಪ್ರಕಾರ, ತುರ್ತುಮಟ್ಟ ಮತ್ತು ಮಾದರಿಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ.",
        },
        {
          title: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಧೋರಣಿಗಳನ್ನು ತೋರಿಸುತ್ತದೆ",
          body: "ಅಧికారಿಗಳು ವಿಭಾಗ, ಟ್ರೆಂಡ್ ಮತ್ತು ನಗರ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ಚಾರ್ಟ್ ಹಾಗೂ ಹೀಟ್ ಮ್ಯಾಪ್ ಮೂಲಕ ನೋಡಬಹುದು.",
        },
        {
          title: "ಪರಿಹಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲಾಗುತ್ತದೆ",
          body: "ನಿರ್ವಹಣಾಧಿಕಾರಿಗಳು ವಿಭಾಗ ಹಂಚಿಕೆ, ಸ್ಥಿತಿ ಅಪ್‌ಡೇಟ್, ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಸಮಯರೇಖೆಯನ್ನು ನಿರ್ವಹಿಸಬಹುದು.",
        },
      ],
      residentEyebrow: "ಬೆಂಗಳೂರು ನಿವಾಸಿಗಳಿಗಾಗಿ",
      residentTitle: "ವೇಗವಾದ ಮತ್ತು ಸಂರಚಿತ ವರದಿ",
      residentBody:
        "ವರ್ಗ ಆಯ್ಕೆ, ಸ್ಥಳ ಮಾಹಿತಿ ಮತ್ತು ಸ್ಪಷ್ಟ ವಿವರಣೆಗಳೊಂದಿಗೆ ಮೊಬೈಲ್ ಅಥವಾ ಡೆಸ್ಕ್‌ಟಾಪ್‌ನಿಂದ ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿ.",
      adminEyebrow: "ನಗರ ಆಡಳಿತಕ್ಕಾಗಿ",
      adminTitle: "ಕಾರ್ಯಾಚರಣೆಯ ಸ್ಪಷ್ಟ ನೋಟ",
      adminBody:
        "ಸಮಸ್ಯೆಗಳ ಧೋರಣಿಗಳು, ನಗರ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಗಳ ಗುಣಮಟ್ಟವನ್ನು ಒಂದೇ ಜಾಗದಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.",
    },
    login: {
      eyebrow: "ಸುರಕ್ಷಿತ ಪ್ರವೇಶ",
      title: "Silicon Sentry ಗೆ ಲಾಗಿನ್ ಆಗಿ",
      body: "ನಾಗರಿಕ ದೂರು ಪ್ರವಾಹ ಅಥವಾ ನಿರ್ವಹಣಾ ನಿಯಂತ್ರಣ ಕೇಂದ್ರಕ್ಕೆ ಹೋಗಲು ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
      userRole: "ಬಳಕೆದಾರ ಲಾಗಿನ್",
      adminRole: "ನಿರ್ವಹಣಾ ಲಾಗಿನ್",
      email: "ಇಮೇಲ್",
      password: "ಪಾಸ್ವರ್ಡ್",
      signingIn: "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
      signInAs: "ಈ ರೀತಿ ಲಾಗಿನ್ ಆಗಿ",
      loginFailed: "ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ.",
    },
    submit: {
      eyebrow: "ಬೆಂಗಳೂರು ಸಮಸ್ಯೆ ವರದಿ",
      title: "ನಕ್ಷೆ ವಿವರಗಳೊಂದಿಗೆ ನಾಗರಿಕ ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿ",
      reportsEyebrow: "ನನ್ನ ವರದಿಗಳು",
      reportsTitle: "ನಿಮ್ಮ ಸಮಸ್ಯೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ವಿಮರ್ಶೆ ಸೇರಿಸಿ",
      reportsBody:
        "ದೂರು ದಾಖಲಾಗಿದ ನಂತರ, ಸಮಸ್ಯೆಯನ್ನು ಹೇಗೆ ನಿರ್ವಹಿಸಲಾಯಿತು ಎಂಬುದರ ಮೇಲೆ ನೀವು ವಿಮರ್ಶೆ ಸೇರಿಸಬಹುದು.",
      loading: "ನಿಮ್ಮ ಸಮಸ್ಯೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
      empty: "ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿಲ್ಲ.",
      reporterLabel: "ಸಲ್ಲಿಸಿದವರು",
      locationLabel: "ಸ್ಥಳ",
      noLocation: "ಸ್ಥಳ ಮಾಹಿತಿ ಸೇರಿಸಲಿಲ್ಲ",
      sentimentLabel: "ಭಾವನೆ",
      assignedLabel: "ಹಂಚಿಕೆ",
      resolutionTitle: "ಪರಿಹಾರ ನವೀಕರಣ",
      timelineTitle: "ಪ್ರಗತಿ ಸಮಯರೇಖೆ",
      noReviews: "ಇನ್ನೂ ವಿಮರ್ಶೆಗಳು ಇಲ್ಲ.",
      attachmentsTitle: "ಸೇರಿಸಿದ ಚಿತ್ರಗಳು",
    },
    form: {
      name: "ಪೂರ್ಣ ಹೆಸರು",
      email: "ಇಮೇಲ್",
      department: "ನಾಗರಿಕ ಇಲಾಖೆ ಅಥವಾ ವಾರ್ಡ್",
      departmentPlaceholder: "BBMP ವಾರ್ಡ್, BWSSB, ಟ್ರಾಫಿಕ್ ಪೊಲೀಸ್, BESCOM...",
      category: "ವರ್ಗ",
      subject: "ವಿಷಯ",
      description: "ವಿವರಣೆ",
      photos: "ಸಮಸ್ಯೆಯ ಚಿತ್ರಗಳು",
      photoHelp: "ಸಮಸ್ಯೆಯನ್ನು ದಾಖಲಿಸಲು ಗರಿಷ್ಠ 3 ಚಿತ್ರಗಳನ್ನು ಸೇರಿಸಿ.",
      removePhoto: "ತೆಗೆದುಹಾಕಿ",
      mapEyebrow: "ನಕ್ಷೆ ಏಕೀಕರಣ",
      mapTitle: "ಸಮಸ್ಯೆಯ ಸ್ಥಳವನ್ನು ಸೇರಿಸಿ",
      useMyLocation: "ನನ್ನ ಸ್ಥಳ ಬಳಸಿ",
      locating: "ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
      locationLabel: "ಸ್ಥಳದ ಹೆಸರು",
      locationPlaceholder: "MG Road signal, Indiranagar 100 Ft Road, Ward office...",
      latitude: "ಅಕ್ಷಾಂಶ",
      longitude: "ರೇಖಾಂಶ",
      submit: "ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿ",
      submitting: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
      success: "ದೂರು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.",
      geolocationUnsupported: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಜಿಯೋಲೊಕೇಶನ್ ಸೌಲಭ್ಯ ಲಭ್ಯವಿಲ್ಲ.",
      geolocationFailed: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಕೈಯಾರೆ ಸೇರಿಸಬಹುದು.",
      photoTypeError: "ದಯವಿಟ್ಟು ಚಿತ್ರ ಫೈಲ್‌ಗಳನ್ನು ಮಾತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
      photoLimitError: "ಒಂದು ಸಮಸ್ಯೆಗೆ ಗರಿಷ್ಠ 3 ಚಿತ್ರಗಳನ್ನು ಮಾತ್ರ ಸೇರಿಸಬಹುದು.",
    },
    review: {
      reviewerName: "ವಿಮರ್ಶಕರ ಹೆಸರು",
      stars: "ನಕ್ಷತ್ರಗಳು",
      comment: "ವಿಮರ್ಶೆ",
      saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...",
      add: "ವಿಮರ್ಶೆ ಸೇರಿಸಿ",
      success: "ವಿಮರ್ಶೆ ದಾಖಲಿಸಲಾಗಿದೆ.",
      failed: "ವಿಮರ್ಶೆ ಸೇರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
    },
    admin: {
      eyebrow: "ಕಾರ್ಯಾಚರಣೆ ಕೇಂದ್ರ",
      titleSuffix: " ಅವರ ನಿಯಂತ್ರಣ ಕೇಂದ್ರ",
      body:
        "ಬೆಂಗಳೂರು ದೂರುಗಳ ಪ್ರಮಾಣ, ಧೋರಣಿಗಳು, ವಿಭಾಗ ಹಂಚಿಕೆ ಮತ್ತು ಪರಿಹಾರ ಪ್ರಗತಿಯನ್ನು ಒಂದೇ ನಿರ್ವಹಣಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಲ್ಲಿ ಗಮನಿಸಿ.",
      totalIssues: "ಒಟ್ಟು ಸಮಸ್ಯೆಗಳು",
      openCases: "ತೆರೆದ ಪ್ರಕರಣಗಳು",
      resolved: "ಪರಿಹರಿಸಿದವು",
      resolutionRate: "ಪರಿಹಾರ ಪ್ರಮಾಣ",
      departmentEyebrow: "ವಿಭಾಗದ ಕಾರ್ಯಕ್ಷಮತೆ",
      departmentTitle: "ಹಂಚಿಕೆ ವಿತರಣೆ",
      departmentName: "ವಿಭಾಗ",
      assignedCount: "ಹಂಚಿಕೆ",
      resolvedCount: "ಪರಿಹರಿಸಿದವು",
      slaCompliance: "SLA ಅನುಸರಣೆ",
      noAssignments: "ಇನ್ನೂ ಯಾವುದೇ ವಿಭಾಗ ಹಂಚಿಕೆ ಇಲ್ಲ.",
      heatEyebrow: "ಸ್ಥಳೀಯ ಬುದ್ಧಿವಂತಿಕೆ",
      heatTitle: "ಸಮಸ್ಯೆ ಹೀಟ್ ಮ್ಯಾಪ್",
      heatBody: "ಬೆಂಗಳೂರು ನಗರದ ದೂರು ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ನಕ್ಷೆಯಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.",
      filtersEyebrow: "ಫಿಲ್ಟರ್ ಮತ್ತು ಹುಡುಕಾಟ",
      filtersTitle: "ಧೋರಣೆ ವಿಶ್ಲೇಷಣಾ ನಿಯಂತ್ರಣಗಳು",
      searchPlaceholder: "ವಿಷಯ, ಸ್ಥಳ ಅಥವಾ ವರದಿದಾರರನ್ನು ಹುಡುಕಿ",
      allStatuses: "ಎಲ್ಲ ಸ್ಥಿತಿಗಳು",
      allCategories: "ಎಲ್ಲ ವರ್ಗಗಳು",
      allAssignments: "ಎಲ್ಲ ಹಂಚಿಕೆಗಳು",
      workflowEyebrow: "ಪರಿಹಾರ ಕಾರ್ಯಪ್ರವಾಹ",
      workflowTitle: "ಸಮಸ್ಯೆ ನಿರ್ವಹಣಾ ಪಟ್ಟಿ",
      loading: "ಸಮಸ್ಯೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
      noMatches: "ಆಯ್ದ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಸಮಸ್ಯೆಗಳಿಲ್ಲ.",
      reporter: "ವರದಿದಾರ",
      sentiment: "ಭಾವನೆ",
      assigned: "ಹಂಚಿಕೆ",
      location: "ಸ್ಥಳ",
      noLocation: "ಸ್ಥಳ ಮಾಹಿತಿ ಸೇರಿಸಲಿಲ್ಲ",
      status: "ಸ್ಥಿತಿ",
      assignedDepartment: "ಹಂಚಿದ ಇಲಾಖೆ",
      resolutionNotes: "ಪರಿಹಾರ ಟಿಪ್ಪಣಿಗಳು",
      resolutionPlaceholder: "ಕೈಗೊಂಡ ಕ್ರಮ, ಮುಂದಿನ ಹಂತಗಳು ಅಥವಾ ಮುಚ್ಚುವಿಕೆ ಟಿಪ್ಪಣಿಗಳನ್ನು ಸೇರಿಸಿ",
      timelineTitle: "ಪ್ರಗತಿ ಸಮಯರೇಖೆ",
      attachmentsTitle: "ಸೇರಿಸಿದ ಚಿತ್ರಗಳು",
    },
    charts: {
      distributionEyebrow: "ವಿತರಣಾ ಚಿತ್ರ",
      byCategory: "ವರ್ಗ ವಿತರಣೆ",
      priorityEyebrow: "ಧೋರಣೆ ನೋಟ",
      byPriority: "ದಾಖಲಿಸಿದವು ವಿರುದ್ಧ ಪರಿಹರಿಸಿದವು (6 ತಿಂಗಳು)",
    },
    heatmap: {
      title: "ಬೆಂಗಳೂರು ಸಮಸ್ಯೆ ಹೀಟ್ ಮ್ಯಾಪ್",
      legendTitle: "ಹೀಟ್ ಮ್ಯಾಪ್ ಸೂಚನೆ",
      legendBody: "ಮಾರ್ಕರ್‌ಗಳು ಬೆಂಗಳೂರಿನ ಮ್ಯಾಪ್ ಮಾಡಿದ ದೂರುಗಳನ್ನು ಆದ್ಯತೆಯ ಆಧಾರದ ಮೇಲೆ ಸಾರಾಂಶಗೊಳಿಸುತ್ತವೆ.",
      high: "ಹೆಚ್ಚು",
      medium: "ಮಧ್ಯಮ",
      low: "ಕಡಿಮೆ",
    },
    shared: {
      roads: "ರಸ್ತೆಗಳು",
      waterSupply: "ನೀರಿನ ಸರಬರಾಜು",
      sanitation: "ಸ್ವಚ್ಛತೆ",
      streetLights: "ರಸ್ತೆ ದೀಪಗಳು",
      publicSafety: "ಸಾರ್ವಜನಿಕ ಭದ್ರತೆ",
      parks: "ಪಾರ್ಕ್ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸ್ಥಳಗಳು",
      publicTransport: "ಸಾರ್ವಜನಿಕ ಸಾರಿಗೆ",
      otherIssue: "ಇತರೆ ನಾಗರಿಕ ಸಮಸ್ಯೆ",
      open: "ತೆರೆದಿದೆ",
      inProgress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
      resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    },
  },
};

copy.hi = {
  ...copy.en,
  app: {
    ...copy.en.app,
    utilityPrimary: "कर्नाटक सरकार नागरिक शिकायत पोर्टल",
    utilitySecondary: "बेंगलुरु शहरी रिपोर्टिंग इंटरफेस",
    languageLabel: "भाषा",
    themeLabel: "थीम",
    lightMode: "लाइट",
    darkMode: "डार्क",
    home: "होम",
    reportIssue: "समस्या दर्ज करें",
    adminHub: "एडमिन हब",
    login: "लॉगिन",
    switchAccount: "खाता बदलें",
    logout: "लॉगआउट",
    eyebrow: "बेंगलुरु के लिए शहर-स्तरीय नागरिक शिकायत दृश्यता",
    subtitle: "जहां सार्वजनिक शिकायत रिपोर्टिंग एकत्रित होती है",
  },
  login: {
    ...copy.en.login,
    eyebrow: "सुरक्षित प्रवेश",
    title: "Silicon Sentry में साइन इन करें",
    body: "नागरिक शिकायत प्रवाह या एडमिन कमांड सेंटर में प्रवेश के लिए भूमिका चुनें।",
    userRole: "यूज़र लॉगिन",
    adminRole: "एडमिन लॉगिन",
    email: "ईमेल",
    password: "पासवर्ड",
    signingIn: "साइन इन हो रहा है...",
    signInAs: "इस रूप में साइन इन करें",
    loginFailed: "लॉगिन विफल हुआ।",
  },
  submit: {
    ...copy.en.submit,
    eyebrow: "बेंगलुरु समस्या रिपोर्टिंग",
    title: "मैप विवरण के साथ नागरिक समस्या दर्ज करें",
    reportsEyebrow: "मेरी रिपोर्ट्स",
    reportsTitle: "अपनी शिकायतें ट्रैक करें और समीक्षा जोड़ें",
    loading: "आपकी शिकायतें लोड हो रही हैं...",
    empty: "आपने अभी तक कोई समस्या दर्ज नहीं की है।",
    reporterLabel: "रिपोर्टर",
    locationLabel: "स्थान",
    noLocation: "कोई स्थान संलग्न नहीं",
    sentimentLabel: "भाव",
    assignedLabel: "असाइन",
    resolutionTitle: "समाधान अपडेट",
    timelineTitle: "प्रगति टाइमलाइन",
    noReviews: "अभी तक कोई समीक्षा नहीं जोड़ी गई।",
    attachmentsTitle: "संलग्न फ़ोटो",
  },
  form: {
    ...copy.en.form,
    name: "पूरा नाम",
    email: "ईमेल",
    department: "नागरिक विभाग या वार्ड",
    category: "श्रेणी",
    subject: "विषय",
    description: "विवरण",
    photos: "समस्या की फ़ोटो",
    photoHelp: "समस्या को दर्ज करने के लिए अधिकतम 3 फ़ोटो जोड़ें।",
    removePhoto: "हटाएं",
    mapEyebrow: "मैप इंटीग्रेशन",
    mapTitle: "समस्या का स्थान जोड़ें",
    useMyLocation: "मेरा स्थान उपयोग करें",
    locating: "स्थान खोजा जा रहा है...",
    locationLabel: "स्थान लेबल",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    submit: "समस्या सबमिट करें",
    submitting: "सबमिट हो रहा है...",
    success: "शिकायत सफलतापूर्वक दर्ज की गई।",
  },
  review: {
    ...copy.en.review,
    reviewerName: "समीक्षक का नाम",
    stars: "स्टार",
    comment: "समीक्षा टिप्पणी",
    saving: "सेव हो रहा है...",
    add: "समीक्षा जोड़ें",
    success: "समीक्षा दर्ज कर ली गई।",
    failed: "समीक्षा जोड़ना संभव नहीं हुआ।",
  },
  admin: {
    ...copy.en.admin,
    eyebrow: "ऑपरेशंस सेंटर",
    titleSuffix: " का कमांड सेंटर",
    body: "बेंगलुरु शिकायत मात्रा, ट्रेंड, विभाग असाइनमेंट और समाधान प्रगति को एक ही एडमिन कार्यक्षेत्र से मॉनिटर करें।",
    totalIssues: "कुल शिकायतें",
    openCases: "खुले मामले",
    resolved: "समाधान हुए",
    resolutionRate: "समाधान दर",
    departmentEyebrow: "विभाग प्रदर्शन",
    departmentTitle: "असाइनमेंट वितरण",
    departmentName: "विभाग",
    assignedCount: "असाइन",
    resolvedCount: "समाधान",
    slaCompliance: "SLA अनुपालन",
    noAssignments: "अभी तक कोई विभाग असाइन नहीं हुआ है।",
    heatEyebrow: "स्थानिक विश्लेषण",
    heatTitle: "शिकायत हीट मैप",
    heatBody: "बेंगलुरु के शिकायत हॉटस्पॉट सीधे मैप पर देखें।",
    filtersEyebrow: "फ़िल्टर और खोज",
    filtersTitle: "ट्रेंड विश्लेषण नियंत्रण",
    searchPlaceholder: "विषय, स्थान या रिपोर्टर खोजें",
    allStatuses: "सभी स्थितियां",
    allCategories: "सभी श्रेणियां",
    allAssignments: "सभी असाइनमेंट",
    workflowEyebrow: "समाधान कार्यप्रवाह",
    workflowTitle: "शिकायत प्रबंधन सूची",
    loading: "शिकायतें लोड हो रही हैं...",
    noMatches: "चुने गए फ़िल्टर से मेल खाने वाली शिकायतें नहीं मिलीं।",
    reporter: "रिपोर्टर",
    sentiment: "भाव",
    assigned: "असाइन",
    location: "स्थान",
    noLocation: "कोई स्थान संलग्न नहीं",
    status: "स्थिति",
    assignedDepartment: "असाइन विभाग",
    resolutionNotes: "समाधान नोट्स",
    timelineTitle: "प्रगति टाइमलाइन",
    attachmentsTitle: "संलग्न फ़ोटो",
  },
  charts: {
    ...copy.en.charts,
    distributionEyebrow: "वितरण",
    byCategory: "श्रेणी वितरण",
    priorityEyebrow: "ट्रेंड मॉनिटर",
    byPriority: "दर्ज बनाम समाधान (6 माह)",
  },
  heatmap: {
    ...copy.en.heatmap,
    title: "बेंगलुरु शिकायत हीट मैप",
    legendTitle: "हीट मैप संकेत",
    legendBody: "मार्कर बेंगलुरु में मैप की गई शिकायतों को प्राथमिकता के आधार पर दर्शाते हैं।",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
  },
  shared: {
    ...copy.en.shared,
    roads: "सड़कें",
    waterSupply: "जल आपूर्ति",
    sanitation: "स्वच्छता",
    streetLights: "स्ट्रीट लाइट",
    publicSafety: "सार्वजनिक सुरक्षा",
    parks: "पार्क और सार्वजनिक स्थान",
    publicTransport: "सार्वजनिक परिवहन",
    otherIssue: "अन्य नागरिक समस्या",
    open: "खुला",
    inProgress: "प्रगति पर",
    resolved: "समाधान हुआ",
  },
};

copy.te = {
  ...copy.en,
  app: {
    ...copy.en.app,
    utilityPrimary: "కర్ణాటక ప్రభుత్వం పౌర ఫిర్యాదు పోర్టల్",
    utilitySecondary: "బెంగళూరు అర్బన్ రిపోర్టింగ్ ఇంటర్‌ఫేస్",
    languageLabel: "భాష",
    themeLabel: "థీమ్",
    lightMode: "లైట్",
    darkMode: "డార్క్",
    home: "హోమ్",
    reportIssue: "సమస్య నివేదించండి",
    adminHub: "అడ్మిన్ హబ్",
    login: "లాగిన్",
    switchAccount: "ఖాతా మార్చండి",
    logout: "లాగౌట్",
    eyebrow: "బెంగళూరుకు నగరస్థాయి పౌర సమస్యల దృశ్యమానం",
    subtitle: "ప్రజా సమస్యల నివేదిక ఒకే వేదికపై",
  },
  login: {
    ...copy.en.login,
    eyebrow: "సురక్షిత ప్రవేశం",
    title: "Silicon Sentryలో సైన్ ఇన్ చేయండి",
    userRole: "యూజర్ లాగిన్",
    adminRole: "అడ్మిన్ లాగిన్",
    signingIn: "సైన్ ఇన్ అవుతోంది...",
    signInAs: "ఈ రూపంలో సైన్ ఇన్ చేయండి",
  },
  submit: {
    ...copy.en.submit,
    eyebrow: "బెంగళూరు సమస్య నివేదిక",
    title: "మ్యాప్ వివరాలతో పౌర సమస్యను సమర్పించండి",
    reportsEyebrow: "నా నివేదికలు",
    reportsTitle: "మీ సమస్యలను ట్రాక్ చేసి సమీక్షలు జోడించండి",
    loading: "మీ సమస్యలు లోడ్ అవుతున్నాయి...",
    empty: "మీరు ఇంకా ఏ సమస్యను సమర్పించలేదు.",
    reporterLabel: "రిపోర్టర్",
    locationLabel: "ప్రదేశం",
    noLocation: "ప్రదేశం జోడించలేదు",
    sentimentLabel: "భావం",
    assignedLabel: "అప్పగించబడింది",
    resolutionTitle: "పరిష్కార నవీకరణ",
    timelineTitle: "పురోగతి టైమ్‌లైన్",
    noReviews: "ఇప్పటివరకు సమీక్షలు లేవు.",
    attachmentsTitle: "జత చేసిన ఫోటోలు",
  },
  form: {
    ...copy.en.form,
    name: "పూర్తి పేరు",
    email: "ఇమెయిల్",
    department: "పౌర విభాగం లేదా వార్డ్",
    category: "వర్గం",
    subject: "విషయం",
    description: "వివరణ",
    photos: "సమస్య ఫోటోలు",
    photoHelp: "సమస్యను నమోదు చేయడానికి గరిష్టంగా 3 ఫోటోలు జోడించండి.",
    removePhoto: "తొలగించు",
    mapEyebrow: "మ్యాప్ ఇంటిగ్రేషన్",
    mapTitle: "సమస్య స్థానాన్ని జోడించండి",
    useMyLocation: "నా స్థానాన్ని ఉపయోగించండి",
    locating: "స్థానం కనుగొంటోంది...",
    locationLabel: "స్థల పేరు",
    latitude: "అక్షాంశం",
    longitude: "రేఖాంశం",
    submit: "సమస్య సమర్పించండి",
    submitting: "సమర్పిస్తోంది...",
    success: "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది.",
  },
  review: {
    ...copy.en.review,
    reviewerName: "సమీక్షకుడి పేరు",
    stars: "స్టార్లు",
    comment: "సమీక్ష వ్యాఖ్య",
    saving: "సేవ్ అవుతోంది...",
    add: "సమీక్ష జోడించండి",
    success: "సమీక్ష నమోదు అయింది.",
  },
  admin: {
    ...copy.en.admin,
    eyebrow: "ఆపరేషన్స్ సెంటర్",
    titleSuffix: " యొక్క కమాండ్ సెంటర్",
    totalIssues: "మొత్తం సమస్యలు",
    openCases: "ఓపెన్ కేసులు",
    resolved: "పరిష్కరించబడినవి",
    resolutionRate: "పరిష్కార రేటు",
    departmentEyebrow: "విభాగ పనితీరు",
    departmentTitle: "అప్పగింత పంపిణీ",
    departmentName: "విభాగం",
    assignedCount: "అప్పగించబడినవి",
    resolvedCount: "పరిష్కరించబడినవి",
    slaCompliance: "SLA అనుసరణ",
    noAssignments: "ఇప్పటికీ ఎలాంటి విభాగ అప్పగింతలు లేవు.",
    heatEyebrow: "భౌగోళిక విశ్లేషణ",
    heatTitle: "సమస్య హీట్ మ్యాప్",
    filtersEyebrow: "ఫిల్టర్‌లు మరియు శోధన",
    filtersTitle: "ట్రెండ్ విశ్లేషణ నియంత్రణలు",
    allStatuses: "అన్ని స్థితులు",
    allCategories: "అన్ని వర్గాలు",
    allAssignments: "అన్ని అప్పగింతలు",
    workflowEyebrow: "పరిష్కార వర్క్‌ఫ్లో",
    workflowTitle: "సమస్య నిర్వహణ జాబితా",
    loading: "సమస్యలు లోడ్ అవుతున్నాయి...",
    noMatches: "ఎంచుకున్న ఫిల్టర్లకు సరిపోయే సమస్యలు లేవు.",
    reporter: "రిపోర్టర్",
    sentiment: "భావం",
    assigned: "అప్పగించబడింది",
    location: "ప్రదేశం",
    noLocation: "ప్రదేశం జోడించలేదు",
    status: "స్థితి",
    assignedDepartment: "అప్పగించిన విభాగం",
    resolutionNotes: "పరిష్కార గమనికలు",
    timelineTitle: "పురోగతి టైమ్‌లైన్",
    attachmentsTitle: "జత చేసిన ఫోటోలు",
  },
  charts: {
    ...copy.en.charts,
    distributionEyebrow: "విభజన",
    byCategory: "వర్గాల పంపిణీ",
    priorityEyebrow: "ట్రెండ్ మానిటర్",
    byPriority: "దాఖలు వర్సెస్ పరిష్కారం (6 నెలలు)",
  },
  heatmap: {
    ...copy.en.heatmap,
    title: "బెంగళూరు సమస్య హీట్ మ్యాప్",
    legendTitle: "హీట్ మ్యాప్ సూచిక",
    legendBody: "మార్కర్లు బెంగళూరులో మ్యాప్ చేసిన ఫిర్యాదులను ప్రాధాన్యత ఆధారంగా చూపిస్తాయి.",
    high: "అధిక",
    medium: "మధ్యస్థ",
    low: "తక్కువ",
  },
  shared: {
    ...copy.en.shared,
    roads: "రోడ్లు",
    waterSupply: "నీటి సరఫరా",
    sanitation: "శుభ్రత",
    streetLights: "వీధి దీపాలు",
    publicSafety: "ప్రజా భద్రత",
    parks: "పార్కులు మరియు ప్రజా ప్రదేశాలు",
    publicTransport: "ప్రజా రవాణా",
    otherIssue: "ఇతర పౌర సమస్య",
    open: "ఓపెన్",
    inProgress: "పురోగతిలో",
    resolved: "పరిష్కరించబడింది",
  },
};

copy.ta = {
  ...copy.en,
  app: {
    ...copy.en.app,
    utilityPrimary: "கர்நாடக அரசு குடிமக்கள் புகார் தளம்",
    utilitySecondary: "பெங்களூரு நகர அறிக்கை இடைமுகம்",
    languageLabel: "மொழி",
    themeLabel: "தீம்",
    lightMode: "ஒளி",
    darkMode: "இருள்",
    home: "முகப்பு",
    reportIssue: "பிரச்சினையை புகாரளிக்கவும்",
    adminHub: "அட்மின் மையம்",
    login: "உள்நுழைவு",
    switchAccount: "கணக்கை மாற்றவும்",
    logout: "வெளியேறு",
    eyebrow: "பெங்களூருக்கான நகர்மட்ட குடிமக்கள் பிரச்சினை பார்வை",
    subtitle: "பொது பிரச்சினை அறிக்கைகள் ஒரே தளத்தில்",
  },
  login: {
    ...copy.en.login,
    eyebrow: "பாதுகாப்பான அணுகல்",
    title: "Silicon Sentry-யில் உள்நுழைக",
    userRole: "பயனர் உள்நுழைவு",
    adminRole: "அட்மின் உள்நுழைவு",
    signingIn: "உள்நுழைகிறது...",
    signInAs: "இவ்வாறு உள்நுழைக",
  },
  submit: {
    ...copy.en.submit,
    eyebrow: "பெங்களூரு பிரச்சினை அறிக்கை",
    title: "வரைபட விவரங்களுடன் குடிமக்கள் பிரச்சினையை சமர்ப்பிக்கவும்",
    reportsEyebrow: "என் அறிக்கைகள்",
    reportsTitle: "உங்கள் புகார்களை கண்காணித்து மதிப்புரைகளை சேர்க்கவும்",
    loading: "உங்கள் பிரச்சினைகள் ஏற்றப்படுகின்றன...",
    empty: "நீங்கள் இதுவரை எந்த பிரச்சினையும் சமர்ப்பிக்கவில்லை.",
    reporterLabel: "அறிக்கையிட்டவர்",
    locationLabel: "இடம்",
    noLocation: "இடம் இணைக்கப்படவில்லை",
    sentimentLabel: "உணர்வு",
    assignedLabel: "ஒதுக்கப்பட்டது",
    resolutionTitle: "தீர்வு புதுப்பிப்பு",
    timelineTitle: "முன்னேற்ற காலவரிசை",
    noReviews: "இன்னும் மதிப்புரைகள் இல்லை.",
    attachmentsTitle: "இணைக்கப்பட்ட புகைப்படங்கள்",
  },
  form: {
    ...copy.en.form,
    name: "முழு பெயர்",
    email: "மின்னஞ்சல்",
    department: "குடிமக்கள் துறை அல்லது வார்டு",
    category: "வகை",
    subject: "பொருள்",
    description: "விளக்கம்",
    photos: "பிரச்சினை புகைப்படங்கள்",
    photoHelp: "பிரச்சினையை பதிவு செய்ய அதிகபட்சம் 3 புகைப்படங்கள் சேர்க்கவும்.",
    removePhoto: "நீக்கு",
    mapEyebrow: "வரைபட இணைப்பு",
    mapTitle: "பிரச்சினை இடத்தை சேர்க்கவும்",
    useMyLocation: "என் இடத்தை பயன்படுத்தவும்",
    locating: "இடம் கண்டறியப்படுகிறது...",
    locationLabel: "இட லேபல்",
    latitude: "அட்சரேகை",
    longitude: "தீர்க்கரேகை",
    submit: "பிரச்சினையை சமர்ப்பிக்கவும்",
    submitting: "சமர்ப்பிக்கப்படுகிறது...",
    success: "புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.",
  },
  review: {
    ...copy.en.review,
    reviewerName: "மதிப்பாய்வாளர் பெயர்",
    stars: "நட்சத்திரங்கள்",
    comment: "மதிப்புரை கருத்து",
    saving: "சேமிக்கப்படுகிறது...",
    add: "மதிப்புரை சேர்க்கவும்",
    success: "மதிப்புரை பதிவு செய்யப்பட்டது.",
  },
  admin: {
    ...copy.en.admin,
    eyebrow: "செயல்பாட்டு மையம்",
    titleSuffix: " அவர்களின் கட்டுப்பாட்டு மையம்",
    totalIssues: "மொத்த பிரச்சினைகள்",
    openCases: "திறந்த வழக்குகள்",
    resolved: "தீர்க்கப்பட்டவை",
    resolutionRate: "தீர்வு விகிதம்",
    departmentEyebrow: "துறை செயல்திறன்",
    departmentTitle: "ஒதுக்கீட்டு பகிர்வு",
    departmentName: "துறை",
    assignedCount: "ஒதுக்கப்பட்டது",
    resolvedCount: "தீர்க்கப்பட்டது",
    slaCompliance: "SLA இணக்கம்",
    noAssignments: "இன்னும் துறை ஒதுக்கீடுகள் இல்லை.",
    heatEyebrow: "புவியியல் நுண்ணறிவு",
    heatTitle: "பிரச்சினை ஹீட் மேப்",
    filtersEyebrow: "வடிகட்டி மற்றும் தேடல்",
    filtersTitle: "போக்கு பகுப்பாய்வு கட்டுப்பாடுகள்",
    allStatuses: "அனைத்து நிலைகளும்",
    allCategories: "அனைத்து வகைகளும்",
    allAssignments: "அனைத்து ஒதுக்கீடுகளும்",
    workflowEyebrow: "தீர்வு பணிப்பாய்",
    workflowTitle: "பிரச்சினை மேலாண்மை பட்டியல்",
    loading: "பிரச்சினைகள் ஏற்றப்படுகின்றன...",
    noMatches: "தேர்ந்தெடுக்கப்பட்ட வடிகட்டிகளுக்கு பொருந்தும் பிரச்சினைகள் இல்லை.",
    reporter: "அறிக்கையிட்டவர்",
    sentiment: "உணர்வு",
    assigned: "ஒதுக்கப்பட்டது",
    location: "இடம்",
    noLocation: "இடம் இணைக்கப்படவில்லை",
    status: "நிலை",
    assignedDepartment: "ஒதுக்கப்பட்ட துறை",
    resolutionNotes: "தீர்வு குறிப்புகள்",
    timelineTitle: "முன்னேற்ற காலவரிசை",
    attachmentsTitle: "இணைக்கப்பட்ட புகைப்படங்கள்",
  },
  charts: {
    ...copy.en.charts,
    distributionEyebrow: "பகிர்வு",
    byCategory: "வகை பகிர்வு",
    priorityEyebrow: "போக்கு கண்காணிப்பு",
    byPriority: "பதிவு vs தீர்வு (6 மாதங்கள்)",
  },
  heatmap: {
    ...copy.en.heatmap,
    title: "பெங்களூரு பிரச்சினை ஹீட் மேப்",
    legendTitle: "ஹீட் மேப் குறிப்பு",
    legendBody: "மார்க்கர்கள் பெங்களூருவில் வரைபடத்தில் உள்ள புகார்களை முன்னுரிமை அடிப்படையில் காட்டுகின்றன.",
    high: "அதிகம்",
    medium: "நடுத்தரம்",
    low: "குறைவு",
  },
  shared: {
    ...copy.en.shared,
    roads: "சாலைகள்",
    waterSupply: "தண்ணீர் வழங்கல்",
    sanitation: "சுகாதாரம்",
    streetLights: "தெரு விளக்குகள்",
    publicSafety: "பொது பாதுகாப்பு",
    parks: "பூங்காக்கள் மற்றும் பொது இடங்கள்",
    publicTransport: "பொது போக்குவரத்து",
    otherIssue: "மற்ற குடிமக்கள் பிரச்சினை",
    open: "திறந்தது",
    inProgress: "நடப்பில்",
    resolved: "தீர்க்கப்பட்டது",
  },
};

copy.ml = {
  ...copy.en,
  app: {
    ...copy.en.app,
    utilityPrimary: "കർണാടക സർക്കാർ പൗരപരാതി പോർട്ടൽ",
    utilitySecondary: "ബെംഗളൂരു നഗര റിപ്പോർട്ടിംഗ് ഇന്റർഫേസ്",
    languageLabel: "ഭാഷ",
    themeLabel: "തീം",
    lightMode: "ലൈറ്റ്",
    darkMode: "ഡാർക്ക്",
    home: "ഹോം",
    reportIssue: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    adminHub: "അഡ്മിൻ ഹബ്",
    login: "ലോഗിൻ",
    switchAccount: "അക്കൗണ്ട് മാറ്റുക",
    logout: "ലോഗൗട്ട്",
    eyebrow: "ബെംഗളൂരുവിനുള്ള നഗരതല പൗര പ്രശ്ന ദൃശ്യത",
    subtitle: "പൊതു പ്രശ്ന റിപ്പോർട്ടിംഗ് ഒരേ വേദിയിൽ",
  },
  login: {
    ...copy.en.login,
    eyebrow: "സുരക്ഷിത പ്രവേശനം",
    title: "Silicon Sentryയിൽ സൈൻ ഇൻ ചെയ്യുക",
    userRole: "യൂസർ ലോഗിൻ",
    adminRole: "അഡ്മിൻ ലോഗിൻ",
    signingIn: "സൈൻ ഇൻ ചെയ്യുന്നു...",
    signInAs: "ഇങ്ങനെ സൈൻ ഇൻ ചെയ്യുക",
  },
  submit: {
    ...copy.en.submit,
    eyebrow: "ബെംഗളൂരു പ്രശ്ന റിപ്പോർട്ടിംഗ്",
    title: "മാപ്പ് വിവരങ്ങളോടെ പൗര പ്രശ്നം സമർപ്പിക്കുക",
    reportsEyebrow: "എന്റെ റിപ്പോർട്ടുകൾ",
    reportsTitle: "നിങ്ങളുടെ പ്രശ്നങ്ങൾ ട്രാക്ക് ചെയ്ത് റിവ്യൂ ചേർക്കുക",
    loading: "നിങ്ങളുടെ പ്രശ്നങ്ങൾ ലോഡ് ചെയ്യുന്നു...",
    empty: "നിങ്ങൾ ഇതുവരെ ഒരു പ്രശ്നവും സമർപ്പിച്ചിട്ടില്ല.",
    reporterLabel: "റിപ്പോർട്ടർ",
    locationLabel: "സ്ഥലം",
    noLocation: "സ്ഥലം ചേർത്തിട്ടില്ല",
    sentimentLabel: "ഭാവം",
    assignedLabel: "അസൈൻ ചെയ്തത്",
    resolutionTitle: "പരിഹാര അപ്ഡേറ്റ്",
    timelineTitle: "പുരോഗതി ടൈംലൈൻ",
    noReviews: "ഇനിയും റിവ്യൂകളില്ല.",
    attachmentsTitle: "അറ്റാച്ച് ചെയ്ത ഫോട്ടോകൾ",
  },
  form: {
    ...copy.en.form,
    name: "പൂർണ്ണ പേര്",
    email: "ഇമെയിൽ",
    department: "പൗര വകുപ്പ് അല്ലെങ്കിൽ വാർഡ്",
    category: "വിഭാഗം",
    subject: "വിഷയം",
    description: "വിവരണം",
    photos: "പ്രശ്നത്തിന്റെ ഫോട്ടോകൾ",
    photoHelp: "പ്രശ്നം രേഖപ്പെടുത്താൻ പരമാവധി 3 ഫോട്ടോകൾ ചേർക്കുക.",
    removePhoto: "നീക്കുക",
    mapEyebrow: "മാപ്പ് ഇന്റഗ്രേഷൻ",
    mapTitle: "പ്രശ്നത്തിന്റെ സ്ഥലം ചേർക്കുക",
    useMyLocation: "എന്റെ സ്ഥലം ഉപയോഗിക്കുക",
    locating: "സ്ഥലം കണ്ടെത്തുന്നു...",
    locationLabel: "സ്ഥല ലേബൽ",
    latitude: "അക്ഷാംശം",
    longitude: "രേഖാംശം",
    submit: "പ്രശ്നം സമർപ്പിക്കുക",
    submitting: "സമർപ്പിക്കുന്നു...",
    success: "പരാതി വിജയകരമായി സമർപ്പിച്ചു.",
  },
  review: {
    ...copy.en.review,
    reviewerName: "റിവ്യൂ ചെയ്യുന്നവരുടെ പേര്",
    stars: "സ്റ്റാർ",
    comment: "റിവ്യൂ അഭിപ്രായം",
    saving: "സേവ് ചെയ്യുന്നു...",
    add: "റിവ്യൂ ചേർക്കുക",
    success: "റിവ്യൂ രേഖപ്പെടുത്തി.",
  },
  admin: {
    ...copy.en.admin,
    eyebrow: "ഓപ്പറേഷൻസ് സെന്റർ",
    titleSuffix: "യുടെ കമാൻഡ് സെന്റർ",
    totalIssues: "ആകെ പ്രശ്നങ്ങൾ",
    openCases: "തുറന്ന കേസുകൾ",
    resolved: "പരിഹരിച്ചതുകൾ",
    resolutionRate: "പരിഹാര നിരക്ക്",
    departmentEyebrow: "വകുപ്പ് പ്രകടനം",
    departmentTitle: "അസൈൻമെന്റ് വിതരണരീതി",
    departmentName: "വകുപ്പ്",
    assignedCount: "അസൈൻ ചെയ്തത്",
    resolvedCount: "പരിഹരിച്ചത്",
    slaCompliance: "SLA അനുസരണം",
    noAssignments: "ഇനിയും വകുപ്പ് അസൈൻമെന്റുകൾ ഇല്ല.",
    heatEyebrow: "സ്ഥലബുദ്ധി",
    heatTitle: "പ്രശ്ന ഹീറ്റ് മാപ്പ്",
    filtersEyebrow: "ഫിൽറ്റർയും തിരച്ചിലും",
    filtersTitle: "ട്രെൻഡ് വിശകലന നിയന്ത്രണങ്ങൾ",
    allStatuses: "എല്ലാ നിലകളും",
    allCategories: "എല്ലാ വിഭാഗങ്ങളും",
    allAssignments: "എല്ലാ അസൈൻമെന്റുകളും",
    workflowEyebrow: "പരിഹാര പ്രവാഹം",
    workflowTitle: "പ്രശ്ന മാനേജ്മെന്റ് പട്ടിക",
    loading: "പ്രശ്നങ്ങൾ ലോഡ് ചെയ്യുന്നു...",
    noMatches: "തിരഞ്ഞെടുത്ത ഫിൽറ്ററുകൾക്ക് അനുയോജ്യമായ പ്രശ്നങ്ങളില്ല.",
    reporter: "റിപ്പോർട്ടർ",
    sentiment: "ഭാവം",
    assigned: "അസൈൻ ചെയ്തത്",
    location: "സ്ഥലം",
    noLocation: "സ്ഥലം ചേർത്തിട്ടില്ല",
    status: "നില",
    assignedDepartment: "അസൈൻ ചെയ്ത വകുപ്പ്",
    resolutionNotes: "പരിഹാര കുറിപ്പുകൾ",
    timelineTitle: "പുരോഗതി ടൈംലൈൻ",
    attachmentsTitle: "അറ്റാച്ച് ചെയ്ത ഫോട്ടോകൾ",
  },
  charts: {
    ...copy.en.charts,
    distributionEyebrow: "വിതരണം",
    byCategory: "വിഭാഗ വിതരണം",
    priorityEyebrow: "ട്രെൻഡ് നിരീക്ഷണം",
    byPriority: "ഫയൽ ചെയ്തത് vs പരിഹരിച്ചത് (6 മാസം)",
  },
  heatmap: {
    ...copy.en.heatmap,
    title: "ബെംഗളൂരു പ്രശ്ന ഹീറ്റ് മാപ്പ്",
    legendTitle: "ഹീറ്റ് മാപ്പ് ലീജൻഡ്",
    legendBody: "മാർക്കറുകൾ ബെംഗളൂരുവിലെ മാപ്പ് ചെയ്ത പരാതികളെ മുൻഗണനയുടെ അടിസ്ഥാനത്തിൽ കാണിക്കുന്നു.",
    high: "ഉയരം",
    medium: "മധ്യം",
    low: "താഴ്ന്നത്",
  },
  shared: {
    ...copy.en.shared,
    roads: "റോഡുകൾ",
    waterSupply: "ജല വിതരണം",
    sanitation: "ശുചിത്വം",
    streetLights: "വീഥി വിളക്കുകൾ",
    publicSafety: "പൊതു സുരക്ഷ",
    parks: "പാർക്കുകളും പൊതുസ്ഥലങ്ങളും",
    publicTransport: "പൊതു ഗതാഗതം",
    otherIssue: "മറ്റ് പൗര പ്രശ്നം",
    open: "തുറന്നത്",
    inProgress: "നടന്നു കൊണ്ടിരിക്കുന്നു",
    resolved: "പരിഹരിച്ചു",
  },
};

copy.en.shared = {
  ...copy.en.shared,
  highPriority: "High",
  mediumPriority: "Medium",
  lowPriority: "Low",
  prioritySuffix: "priority",
  timelineCreated: "Created",
  timelineAssigned: "Assigned",
  timelineStatusUpdated: "Status Updated",
  timelineResolutionNote: "Resolution Note",
  timelineCreatedDetail: "Complaint submitted by citizen",
  timelineAssignedTo: "Assigned to",
  timelineTo: "to",
};

copy.en.app = {
  ...copy.en.app,
  userHub: "User Hub",
};

copy.hi.app = {
  ...copy.hi.app,
  userHub: "यूज़र हब",
};

copy.te.app = {
  ...copy.te.app,
  userHub: "యూజర్ హబ్",
};

copy.ta.app = {
  ...copy.ta.app,
  userHub: "பயனர் மையம்",
};

copy.ml.app = {
  ...copy.ml.app,
  userHub: "യൂസർ ഹബ്",
};

copy.kn.app = {
  ...copy.kn.app,
  userHub: "ಬಳಕೆದಾರ ಕೇಂದ್ರ",
};

copy.hi.shared = {
  ...copy.hi.shared,
  highPriority: "उच्च",
  mediumPriority: "मध्यम",
  lowPriority: "कम",
  prioritySuffix: "प्राथमिकता",
  timelineCreated: "बनाया गया",
  timelineAssigned: "असाइन किया गया",
  timelineStatusUpdated: "स्थिति अपडेट",
  timelineResolutionNote: "समाधान नोट",
  timelineCreatedDetail: "शिकायत नागरिक द्वारा दर्ज की गई",
  timelineAssignedTo: "असाइन किया गया",
  timelineTo: "से",
};

copy.te.shared = {
  ...copy.te.shared,
  highPriority: "అధిక",
  mediumPriority: "మధ్యస్థ",
  lowPriority: "తక్కువ",
  prioritySuffix: "ప్రాధాన్యత",
  timelineCreated: "సృష్టించబడింది",
  timelineAssigned: "అప్పగించబడింది",
  timelineStatusUpdated: "స్థితి నవీకరణ",
  timelineResolutionNote: "పరిష్కార గమనిక",
  timelineCreatedDetail: "పౌరుడు ఫిర్యాదు సమర్పించాడు",
  timelineAssignedTo: "అప్పగించబడింది",
  timelineTo: "కు",
};

copy.ta.shared = {
  ...copy.ta.shared,
  highPriority: "அதிக",
  mediumPriority: "நடுத்தரம்",
  lowPriority: "குறைவு",
  prioritySuffix: "முன்னுரிமை",
  timelineCreated: "உருவாக்கப்பட்டது",
  timelineAssigned: "ஒதுக்கப்பட்டது",
  timelineStatusUpdated: "நிலை புதுப்பிப்பு",
  timelineResolutionNote: "தீர்வு குறிப்பு",
  timelineCreatedDetail: "புகார் குடிமகனால் சமர்ப்பிக்கப்பட்டது",
  timelineAssignedTo: "ஒதுக்கப்பட்டது",
  timelineTo: "இருந்து",
};

copy.ml.shared = {
  ...copy.ml.shared,
  highPriority: "ഉയർന്ന",
  mediumPriority: "ഇടത്തരം",
  lowPriority: "കുറഞ്ഞ",
  prioritySuffix: "മുൻഗണന",
  timelineCreated: "സൃഷ്ടിച്ചു",
  timelineAssigned: "അസൈൻ ചെയ്തു",
  timelineStatusUpdated: "നില അപ്ഡേറ്റ്",
  timelineResolutionNote: "പരിഹാര കുറിപ്പ്",
  timelineCreatedDetail: "പൗരൻ പരാതി സമർപ്പിച്ചു",
  timelineAssignedTo: "അസൈൻ ചെയ്തത്",
  timelineTo: "മുതൽ",
};

copy.hi.home = {
  ...copy.en.home,
  eyebrow: "राष्ट्रीय पोर्टल प्रेरित नागरिक अनुभव",
  title: "बेंगलुरु भर की सार्वजनिक समस्याओं को स्पष्टता और संरचना के साथ रिपोर्ट और मॉनिटर करें।",
  description:
    "Silicon Sentry नागरिकों को सड़क, पानी, स्वच्छता, सुरक्षा और बुनियादी ढांचे से जुड़ी समस्याओं को दर्ज करने में मदद करता है, जबकि अधिकारियों को यह समझने में सहायता देता है कि कहां ध्यान देने की सबसे अधिक आवश्यकता है।",
  primaryAction: "समस्या दर्ज करें",
  secondaryAction: "एडमिन हब खोलें",
  mapEyebrow: "सार्वजनिक सेवा दृश्य",
  metrics: [
    { title: "जियो-टैग्ड इनटेक", body: "बेंगलुरु के फील्ड मुद्दों को तेजी से रूट करने के लिए लोकेशन जोड़ें।" },
    { title: "श्रेणी आधारित रूटिंग", body: "सड़क, पानी, स्वच्छता, सुरक्षा और अन्य श्रेणियों में शिकायतें व्यवस्थित करें।" },
    { title: "हीट मैप निगरानी", body: "शहर में शिकायतों के सघन क्षेत्रों को जल्दी पहचानें।" },
  ],
  chips: ["सड़कें", "जल आपूर्ति", "स्वच्छता", "स्ट्रीट लाइट", "सार्वजनिक सुरक्षा", "सार्वजनिक परिवहन"],
  problemEyebrow: "समस्या विवरण",
  problemTitle: "यह मंच क्यों महत्वपूर्ण है",
  problemBodyOne:
    "सरकारों को बुनियादी ढांचे, स्वच्छता, उपयोगिताओं, परिवहन और सार्वजनिक सेवाओं से जुड़ी बड़ी संख्या में शिकायतें मिलती हैं। मैनुअल प्रोसेसिंग के कारण इन शिकायतों को वर्गीकृत करना, प्राथमिकता देना और समय पर हल करना कठिन हो जाता है।",
  problemBodyTwo:
    "Silicon Sentry अधिकारियों को तेजी से प्रतिक्रिया देने, दोहराए जाने वाले पैटर्न पहचानने और जवाबदेही बढ़ाने में मदद करता है।",
  challengeEyebrow: "डिज़ाइन चुनौती",
  challengeTitle: "एआई-सहायित शिकायत संचालन",
  challengeBody:
    "यह प्लेटफ़ॉर्म प्राकृतिक भाषा प्रसंस्करण के माध्यम से नागरिक शिकायतों का विश्लेषण करता है, हॉटस्पॉट और ट्रेंड दिखाता है, और प्रशासन को समाधान प्रगति ट्रैक करने के लिए एकीकृत डैशबोर्ड प्रदान करता है।",
  howEyebrow: "यह कैसे काम करता है",
  howTitle: "शिकायत सबमिशन से समाधान ट्रैकिंग तक",
  steps: [
    { title: "नागरिक शिकायत दर्ज करता है", body: "नागरिक श्रेणी, विवरण और वैकल्पिक लोकेशन के साथ समस्या दर्ज करते हैं।" },
    { title: "सिस्टम वर्गीकरण और प्राथमिकता तय करता है", body: "स्ट्रक्चर्ड इनपुट और NLP लॉजिक शिकायत के प्रकार, तात्कालिकता और संभावित क्लस्टर पहचानते हैं।" },
    { title: "डैशबोर्ड ट्रेंड दिखाता है", body: "अधिकारी चार्ट और हीट मैप के माध्यम से श्रेणी ट्रेंड, विभागीय लोड और हॉटस्पॉट मॉनिटर करते हैं।" },
    { title: "समाधान ट्रैक किया जाता है", body: "एडमिन विभाग असाइन करते हैं, स्टेटस अपडेट करते हैं, नोट्स जोड़ते हैं और टाइमलाइन बनाए रखते हैं।" },
  ],
  residentEyebrow: "बेंगलुरु नागरिकों के लिए",
  residentTitle: "तेज़ और संरचित रिपोर्टिंग",
  residentBody: "मोबाइल या डेस्कटॉप से श्रेणी चयन, लोकेशन संदर्भ और स्पष्ट विवरण के साथ समस्याएं दर्ज करें।",
  adminEyebrow: "शहर प्रशासन के लिए",
  adminTitle: "ऑपरेशन का स्पष्ट दृश्य",
  adminBody: "शिकायत ट्रेंड, शहर के हॉटस्पॉट और प्रतिक्रिया गुणवत्ता को एक ही जगह से मॉनिटर करें।",
};

copy.te.home = {
  ...copy.en.home,
  eyebrow: "జాతీయ పోర్టల్ ప్రేరణతో పౌర అనుభవం",
  title: "బెంగళూరు అంతటా ప్రజా సమస్యలను స్పష్టతతో మరియు వ్యవస్థతో నివేదించి పర్యవేక్షించండి.",
  description:
    "Silicon Sentry పౌరులకు రోడ్లు, నీరు, శుభ్రత, భద్రత మరియు మౌలిక సదుపాయాల సమస్యలను నమోదు చేయడంలో సహాయపడుతుంది. అలాగే అధికారులకు ఎక్కడ శ్రద్ధ అవసరమో స్పష్టంగా చూపిస్తుంది.",
  primaryAction: "సమస్య నివేదించండి",
  secondaryAction: "అడ్మిన్ హబ్ తెరవండి",
  mapEyebrow: "ప్రజా సేవా వీక్షణం",
  problemEyebrow: "సమస్య వివరణ",
  problemTitle: "ఈ వేదిక ఎందుకు ముఖ్యమైనది",
  problemBodyOne:
    "ప్రభుత్వాలకు మౌలిక సదుపాయాలు, శుభ్రత, యుటిలిటీలు, రవాణా మరియు ప్రజా సేవలకు సంబంధించిన అనేక ఫిర్యాదులు వస్తుంటాయి. చేతి ప్రక్రియల వల్ల వాటిని వర్గీకరించడం, ప్రాధాన్యత ఇవ్వడం, త్వరగా పరిష్కరించడం కష్టమవుతుంది.",
  problemBodyTwo:
    "Silicon Sentry అధికారులకు వేగంగా స్పందించడానికి, పునరావృత నమూనాలను గుర్తించడానికి, బాధ్యతను పెంచడానికి సహాయపడుతుంది.",
  challengeEyebrow: "డిజైన్ సవాలు",
  challengeTitle: "AI సహాయంతో ఫిర్యాదు నిర్వహణ",
  challengeBody:
    "ఈ ప్లాట్‌ఫారం సహజ భాషా ప్రాసెసింగ్ ద్వారా పౌర ఫిర్యాదులను విశ్లేషించి, హాట్‌స్పాట్‌లు మరియు ట్రెండ్‌లను చూపించి, పరిష్కార పురోగతిని ట్రాక్ చేసే అడ్మిన్ డ్యాష్‌బోర్డ్‌ను అందిస్తుంది.",
  howEyebrow: "ఇది ఎలా పనిచేస్తుంది",
  howTitle: "ఫిర్యాదు సమర్పణ నుండి పరిష్కార ట్రాకింగ్ వరకు",
  residentEyebrow: "బెంగళూరు పౌరుల కోసం",
  residentTitle: "వేగవంతమైన, క్రమబద్ధమైన నివేదిక",
  adminEyebrow: "నగర పాలన కోసం",
  adminTitle: "స్పష్టమైన ఆపరేషనల్ దృశ్యం",
};

copy.ta.home = {
  ...copy.en.home,
  eyebrow: "தேசிய போர்டல் தூண்டப்பட்ட குடிமக்கள் அனுபவம்",
  title: "பெங்களூரு முழுவதும் உள்ள பொது பிரச்சினைகளை தெளிவாகவும் ஒழுங்காகவும் பதிவு செய்து கண்காணிக்கவும்.",
  description:
    "Silicon Sentry குடிமக்கள் சாலை, நீர், சுகாதாரம், பாதுகாப்பு மற்றும் உட்கட்டமைப்பு பிரச்சினைகளை பதிவு செய்ய உதவுகிறது; அதிகாரிகள் கவனம் தேவைப்படும் பகுதிகளை தெளிவாக பார்க்கவும் உதவுகிறது.",
  primaryAction: "பிரச்சினையை பதிவு செய்யவும்",
  secondaryAction: "அட்மின் ஹப் திறக்கவும்",
  mapEyebrow: "பொது சேவை காட்சி",
  problemEyebrow: "பிரச்சினை விளக்கம்",
  problemTitle: "இந்த தளம் ஏன் முக்கியமானது",
  problemBodyOne:
    "அரசுகளுக்கு உட்கட்டமைப்பு, சுகாதாரம், பயன்பாடுகள், போக்குவரத்து மற்றும் பொது சேவைகள் தொடர்பான அதிக அளவிலான புகார்கள் கிடைக்கின்றன. கையேடு செயல்முறைகள் காரணமாக அவற்றை வகைப்படுத்தவும், முன்னுரிமை அளிக்கவும், விரைவாக தீர்க்கவும் கடினமாகிறது.",
  problemBodyTwo:
    "Silicon Sentry அதிகாரிகள் விரைவாக பதிலளிக்கவும், மீண்டும் மீண்டும் தோன்றும் வடிவங்களை கண்டறியவும், பொறுப்புணர்வை மேம்படுத்தவும் உதவுகிறது.",
  challengeEyebrow: "டிசைன் சவால்",
  challengeTitle: "AI உதவியுடன் புகார் செயல்பாடு",
  challengeBody:
    "இந்த தளம் இயற்கை மொழி செயலாக்கத்தை பயன்படுத்தி குடிமக்கள் புகார்களை பகுப்பாய்வு செய்து, ஹாட்ஸ்பாட் மற்றும் போக்குகளை காட்டி, தீர்வு முன்னேற்றத்தை கண்காணிக்கும் நிர்வாக டாஷ்போர்டை வழங்குகிறது.",
  howEyebrow: "இது எப்படி செயல்படுகிறது",
  howTitle: "புகார் சமர்ப்பிப்பில் இருந்து தீர்வு கண்காணிப்புவரை",
  residentEyebrow: "பெங்களூரு குடிமக்களுக்காக",
  residentTitle: "வேகமான மற்றும் கட்டமைக்கப்பட்ட பதிவு",
  adminEyebrow: "நகர நிர்வாகத்திற்காக",
  adminTitle: "தெளிவான செயல்பாட்டு பார்வை",
};

copy.ml.home = {
  ...copy.en.home,
  eyebrow: "ദേശീയ പോർട്ടൽ പ്രചോദിത പൗരാനുഭവം",
  title: "ബെംഗളൂരു മുഴുവൻ പൊതുപ്രശ്നങ്ങളെ വ്യക്തതയോടും ക്രമത്തോടും കൂടി റിപ്പോർട്ട് ചെയ്ത് നിരീക്ഷിക്കുക.",
  description:
    "Silicon Sentry പൗരന്മാർക്ക് റോഡ്, വെള്ളം, ശുചിത്വം, സുരക്ഷ, അടിസ്ഥാനസൗകര്യം എന്നിവയുമായി ബന്ധപ്പെട്ട പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യാൻ സഹായിക്കുന്നു. അതേ സമയം അധികൃതർക്ക് എവിടെയാണ് കൂടുതൽ ശ്രദ്ധ വേണ്ടതെന്ന് വ്യക്തമായി മനസ്സിലാക്കാനും സഹായിക്കുന്നു.",
  primaryAction: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
  secondaryAction: "അഡ്മിൻ ഹബ് തുറക്കുക",
  mapEyebrow: "പൊതു സേവന ദൃശ്യം",
  problemEyebrow: "പ്രശ്ന വിശദീകരണം",
  problemTitle: "ഈ പ്ലാറ്റ്ഫോം എന്തുകൊണ്ട് പ്രധാനമാണ്",
  problemBodyOne:
    "അടിസ്ഥാനസൗകര്യം, ശുചിത്വം, യൂട്ടിലിറ്റികൾ, ഗതാഗതം, പൊതുസേവനങ്ങൾ എന്നിവയുമായി ബന്ധപ്പെട്ട വലിയ തോതിലുള്ള പരാതികൾ സർക്കാരുകൾക്ക് ലഭിക്കുന്നു. മാനുവൽ പ്രോസസ്സിംഗിന്റെ കാരണം അവയെ വർഗ്ഗീകരിക്കുകയും മുൻഗണന നല്കുകയും വേഗത്തിൽ പരിഹരിക്കുകയും ചെയ്യുന്നത് ബുദ്ധിമുട്ടാണ്.",
  problemBodyTwo:
    "Silicon Sentry അധികാരികൾക്ക് വേഗത്തിൽ പ്രതികരിക്കാനും ആവർത്തിക്കുന്ന രീതികളെ കണ്ടെത്താനും ഉത്തരവാദിത്തം വർധിപ്പിക്കാനും സഹായിക്കുന്നു.",
  challengeEyebrow: "ഡിസൈൻ വെല്ലുവിളി",
  challengeTitle: "AI സഹായത്തോടെയുള്ള പരാതി പ്രവർത്തനം",
  challengeBody:
    "ഈ പ്ലാറ്റ്ഫോം നാചുറൽ ലാംഗ്വേജ് പ്രോസസ്സിംഗ് ഉപയോഗിച്ച് പൗരപരാതികളെ വിശകലനം ചെയ്യുകയും ഹോട്ട്സ്പോട്ടുകളും ട്രെൻഡുകളും കണ്ടെത്തുകയും പരിഹാര പുരോഗതി നിരീക്ഷിക്കുന്ന അഡ്മിൻ ഡാഷ്ബോർഡ് നൽകുകയും ചെയ്യുന്നു.",
  howEyebrow: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
  howTitle: "പരാതി സമർപ്പണത്തിൽ നിന്ന് പരിഹാര നിരീക്ഷണം വരെ",
  residentEyebrow: "ബെംഗളൂരു പൗരന്മാർക്കായി",
  residentTitle: "വേഗത്തിലുള്ള ഘടനാപരമായ റിപ്പോർട്ടിംഗ്",
  adminEyebrow: "നഗര ഭരണത്തിനായി",
  adminTitle: "വ്യക്തമായ ഓപ്പറേഷൻസ് ദൃശ്യവൽക്കരണം",
};

export default copy;
